[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "forge-python"
version = "0.0.11"
authors = [{ name = "Forge Software Inc.", email = "developers@theforge.bio" }]
description = "Python client library for theforge.bio API and link."
keywords = ['api', 'client', 'forge', 'theforge.bio']
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests>=2.25.1",
    "pandas>=1.2.3",
    "numpy>=1.20.1",
    "rich>=9.11.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/forge-industrial"
"Bug Tracker" = "https://github.com/forge-industrial/issues"
