[tool.poetry]
name = "GoogleTable"
# version = major.minor.maintenance (крупные изменения.добавление фунционала без нарушения совместимости,исправление багов)
version = "1.1.2"
description = "The module that collects data from the Google table"
authors = ["DaniEruDai <DaniEruDai@gmail.com>"]
readme = "README.md"

keywords = ["Google", "Table","Google Table","Google Sheets"]

[tool.poetry.dependencies]

requests = '^2.28.1'
pandas = '^1.5.2'
python = "^3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


