[tool.poetry]
name = "sphinxcontrib-specs"
version = "1.0.4"
description = "Extensions for building Specializations content."
authors = ["Ashley Trinh <ashley@hackbrightacademy.com>"]
license = "MPL-2.0"
packages = [{ include = "sphinxcontrib", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.1.2"
mypy = "^0.961"
html5lib = "^1.1"
Sphinx = "^5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
