[tool.poetry]
name = "nasbio"
version = "0.1.24"
description = ""
authors = ["Kah Wai LIM <kahwai222@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.87.0"
pika = "^1.3.1"
sqlalchemy = "^1.4.43"
strawberry-graphql = {extras = ["fastapi"], version = "^0.142.2"}
uvicorn = {extras = ["standard"], version = "^0.19.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
