[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aiohere"
version = "2.0.0"
description = "Asynchronous Python client for the HERE API"
license = "MIT"
authors = ["Kevin Stillhammer <kevin.stillhammer@gmail.com>"]
readme = "README.md"
repository = "http://github.com/eifinger/aiohere"
keywords = [
    "aiohttp",
    "asyncio",
    "here"
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License"
]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.3"
frozenlist = "^1.3.3" # Remove if aiohttp->aiosignal uses >1.1.0
async-timeout = "^4.0.2"
yarl = "^1.8.1"

[tool.poetry.group.dev.dependencies]
aresponses = "2.1.6"
black = "22.10.0"
blacken-docs = "^1.12.1"
coverage = {version = "^6.5", extras = ["toml"]}
bandit = "^1.7.2"
codecov = "2.1.12"
codespell = "^2.2.2"
darglint = "^1.8.1"
flake8 = "4.0.1"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.10.27"
flake8-builtins = "^2.0.1"
flake8-comprehensions = "^3.10.1"
flake8-docstrings = "^1.6.0"
flake8-eradicate = "^1.4.0"
flake8-markdown = "^0.3.0"
flake8-simplify = "^0.19.3"
mypy = "0.991"
pre-commit = "2.20.0"
pre-commit-hooks = "^4.3.0"
pytest = "7.2.0"
pytest-cov = "4.0.0"
pytest-asyncio = "0.20.2"
pytest-mock = "3.10.0"
pylint = "2.15.5"
pyupgrade = "^3.2.2"
safety = "^2.3.1"
vulture = "^2.6"
yamllint = "^1.28.0"

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing --cov-report xml --cov=aiohere tests"

[tool.coverage.report]
show_missing = true
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.vulture]
min_confidence = 80
paths = ["aiohere", "tests"]

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
build_command = "pip install poetry && poetry build"
branch = "main"
